name: sync-preview
on:
  push:
    branches:
      - master
jobs:
  sync-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: use node 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: sync preview
        run: sh .github/scripts/sync.sh latest preview
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
